SAMPLE_PRODUCTS = [
    {"id": 1, "title": "Red Sequin Gown", "tags": ["party", "evening"]},
    {"id": 2, "title": "Black Cocktail Dress", "tags": ["cocktail", "party"]},
    {"id": 3, "title": "Red Maxi Dress", "tags": ["casual", "summer"]},
    {"id": 4, "title": "Blue Denim Jacket", "tags": ["casual", "winter"]},
    {"id": 5, "title": "White Formal Shirt", "tags": ["formal", "office"]},
    {"id": 6, "title": "Green Floral Dress", "tags": ["summer", "casual"]},
    {"id": 7, "title": "Golden Party Heels", "tags": ["party", "shoes"]},
    {"id": 8, "title": "Black Leather Jacket", "tags": ["winter", "fashion"]},
    {"id": 9, "title": "Red Bodycon Dress", "tags": ["party", "club"]},
    {"id": 10, "title": "Navy Blue Blazer", "tags": ["formal", "office"]},
    {"id": 11, "title": "Pink Evening Gown", "tags": ["evening", "party"]},
    {"id": 12, "title": "Yellow Summer Dress", "tags": ["summer"]},
    {"id": 13, "title": "Grey Hoodie", "tags": ["casual", "winter"]},
    {"id": 14, "title": "White Sneakers", "tags": ["casual", "shoes"]},
    {"id": 15, "title": "Black Party Skirt", "tags": ["party"]},
    {"id": 16, "title": "Red High Heels", "tags": ["party", "shoes"]},
    {"id": 17, "title": "Blue Party Dress", "tags": ["party"]},
    {"id": 18, "title": "Silver Evening Clutch", "tags": ["evening", "accessory"]},
    {"id": 19, "title": "Maroon Velvet Gown", "tags": ["party", "evening"]},
    {"id": 20, "title": "Peach Summer Top", "tags": ["summer", "casual"]},
    {"id": 21, "title": "Black Tuxedo Suit", "tags": ["formal", "party"]},
    {"id": 22, "title": "Red Saree", "tags": ["traditional", "party"]},
    {"id": 23, "title": "Golden Ethnic Lehenga", "tags": ["wedding", "party"]},
    {"id": 24, "title": "White Party Kurti", "tags": ["party", "ethnic"]},
    {"id": 25, "title": "Black Party Shoes", "tags": ["party", "shoes"]},
    {"id": 26, "title": "Red Evening Scarf", "tags": ["evening", "accessory"]},
    {"id": 27, "title": "Blue Casual Shirt", "tags": ["casual"]},
    {"id": 28, "title": "Pink Party Sandals", "tags": ["party", "shoes"]},
    {"id": 29, "title": "Orange Summer Skirt", "tags": ["summer"]},
    {"id": 30, "title": "Brown Leather Belt", "tags": ["accessory"]},
    {"id": 31, "title": "Purple Party Dress", "tags": ["party"]},
    {"id": 32, "title": "Red Wedding Gown", "tags": ["wedding", "party"]},
    {"id": 33, "title": "Black Evening Coat", "tags": ["evening", "winter"]},
    {"id": 34, "title": "Golden Party Necklace", "tags": ["party", "accessory"]},
    {"id": 35, "title": "White Summer Hat", "tags": ["summer", "accessory"]},
    {"id": 36, "title": "Red Party Jumpsuit", "tags": ["party"]},
    {"id": 37, "title": "Blue Evening Dress", "tags": ["evening"]},
    {"id": 38, "title": "Black Party Blouse", "tags": ["party"]},
    {"id": 39, "title": "Red Party Saree", "tags": ["party", "traditional"]},
    {"id": 40, "title": "Silver Party Gown", "tags": ["party", "evening"]},
    {"id": 41, "title": "Pink Summer Dress", "tags": ["summer", "casual"]},
    {"id": 42, "title": "Blue Winter Coat", "tags": ["winter", "formal"]},
    {"id": 43, "title": "Black Office Trousers", "tags": ["formal", "office"]},
    {"id": 44, "title": "Green Party Dress", "tags": ["party"]},
    {"id": 45, "title": "White Casual Top", "tags": ["casual", "summer"]},
    {"id": 46, "title": "Red Ethnic Kurta", "tags": ["traditional", "party"]},
    {"id": 47, "title": "Blue Wedding Suit", "tags": ["wedding", "formal"]},
    {"id": 48, "title": "Golden Summer Sandals", "tags": ["summer", "shoes"]},
    {"id": 49, "title": "Black Evening Heels", "tags": ["evening", "shoes"]},
    {"id": 50, "title": "Pink Party Dress", "tags": ["party"]},
    {"id": 51, "title": "Red Summer Skirt", "tags": ["summer", "casual"]},
    {"id": 52, "title": "Grey Winter Sweater", "tags": ["winter", "casual"]},
    {"id": 53, "title": "Black Formal Shoes", "tags": ["formal", "office", "shoes"]},
    {"id": 54, "title": "Blue Party Top", "tags": ["party"]},
    {"id": 55, "title": "White Summer Dress", "tags": ["summer"]},
    {"id": 56, "title": "Purple Evening Gown", "tags": ["evening"]},
    {"id": 57, "title": "Red Casual T-Shirt", "tags": ["casual"]},
    {"id": 58, "title": "Black Winter Boots", "tags": ["winter", "shoes"]},
    {"id": 59, "title": "Golden Wedding Lehenga", "tags": ["wedding", "party"]},
    {"id": 60, "title": "White Formal Blazer", "tags": ["formal", "office"]},
    {"id": 61, "title": "Blue Casual Shorts", "tags": ["casual", "summer"]},
    {"id": 62, "title": "Red Party Skirt", "tags": ["party"]},
    {"id": 63, "title": "Black Ethnic Saree", "tags": ["traditional", "party"]},
    {"id": 64, "title": "Pink Summer Top", "tags": ["summer"]},
    {"id": 65, "title": "Blue Winter Scarf", "tags": ["winter", "accessory"]},
    {"id": 66, "title": "Green Evening Dress", "tags": ["evening"]},
    {"id": 67, "title": "Red Wedding Saree", "tags": ["wedding", "traditional"]},
    {"id": 68, "title": "Black Party Blazer", "tags": ["party"]},
    {"id": 69, "title": "White Casual Sneakers", "tags": ["casual", "shoes"]},
    {"id": 70, "title": "Purple Party Shoes", "tags": ["party", "shoes"]},
    {"id": 71, "title": "Blue Summer Dress", "tags": ["summer"]},
    {"id": 72, "title": "Golden Evening Heels", "tags": ["evening", "shoes"]},
    {"id": 73, "title": "Red Formal Shirt", "tags": ["formal", "office"]},
    {"id": 74, "title": "Black Casual Jeans", "tags": ["casual"]},
    {"id": 75, "title": "White Party Dress", "tags": ["party"]},
    {"id": 76, "title": "Blue Wedding Gown", "tags": ["wedding", "party"]},
    {"id": 77, "title": "Pink Winter Coat", "tags": ["winter", "casual"]},
    {"id": 78, "title": "Red Summer Shorts", "tags": ["summer", "casual"]},
    {"id": 79, "title": "Black Evening Gown", "tags": ["evening"]},
    {"id": 80, "title": "Golden Party Clutch", "tags": ["party", "accessory"]},
    {"id": 81, "title": "Blue Office Skirt", "tags": ["formal", "office"]},
    {"id": 82, "title": "White Ethnic Lehenga", "tags": ["traditional", "wedding"]},
    {"id": 83, "title": "Red Summer Hat", "tags": ["summer", "accessory"]},
    {"id": 84, "title": "Black Party Trousers", "tags": ["party"]},
    {"id": 85, "title": "Pink Evening Sandals", "tags": ["evening", "shoes"]},
    {"id": 86, "title": "Blue Casual Hoodie", "tags": ["casual"]},
    {"id": 87, "title": "Golden Wedding Shoes", "tags": ["wedding", "shoes"]},
    {"id": 88, "title": "White Summer Blouse", "tags": ["summer"]},
    {"id": 89, "title": "Red Party Gown", "tags": ["party"]},
    {"id": 90, "title": "Black Winter Coat", "tags": ["winter"]},
    {"id": 91, "title": "Purple Casual Dress", "tags": ["casual"]},
    {"id": 92, "title": "Blue Party Shoes", "tags": ["party", "shoes"]},
    {"id": 93, "title": "Green Summer Dress", "tags": ["summer"]},
    {"id": 94, "title": "Red Evening Blouse", "tags": ["evening"]},
    {"id": 95, "title": "Black Formal Pants", "tags": ["formal", "office"]},
    {"id": 96, "title": "Golden Party Earrings", "tags": ["party", "accessory"]},
    {"id": 97, "title": "White Wedding Dress", "tags": ["wedding", "formal"]},
    {"id": 98, "title": "Blue Summer Top", "tags": ["summer"]},
    {"id": 99, "title": "Red Party Pants", "tags": ["party"]},
    {"id": 100, "title": "Black Evening Clutch", "tags": ["evening", "accessory"]}
]
